### ISSUE TITLE
Empty ref.geojson returned

### ISSUE THREAD

**Issue by Spiruel** [PlatformStories/chip-from-vrt#1]
When attempting a working example, running the chip-from-vrt task on a custom catID and geojson, the following ref.geojson is the only output returned:

{"type": "FeatureCollection", "features": []}
 
Please could you explain what's going wrong/provide a MWE?

Cheers

**Comment by naldeborgh7575** [comment]
Hi- can you tell me what your input was (excluding any credentials). Also were the image(s) and geojson in the same projection?

**Comment by Spiruel** [comment]
I found that I had the image in the wrong projection. The script is now working as intended. Many thanks!
