### ISSUE TITLE
Is it possible to chain the output of previous tasks into chip-from-vrt?

### ISSUE THREAD

**Issue by Spiruel** [PlatformStories/chip-from-vrt#2]
For example, can the output from AOP_Strip_Processor task be provided to this task? I am only able to specify the inputs manually.
Thanks

**Comment by naldeborgh7575** [comment]
No, at this point you need to provide the entire path to the image (including the file itself) as opposed to the directory. This is because the task doesn't mount any images to the workers and the vrt creation process requires the image name.

**Comment by Spiruel** [comment]
No problem - thanks for the clarification.
